/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./components/Appbar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppliedFilters: typeof import('./components/body/AppliedFilters.vue')['default']
    CardGrid: typeof import('./components/body/CardGrid.vue')['default']
    CustomSnackbar: typeof import('./components/menu/CustomSnackbar.vue')['default']
    Favorites: typeof import('./components/Favorites.vue')['default']
    FilterPanel: typeof import('./components/body/FilterPanel.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    LogoutDialog: typeof import('./components/menu/LogoutDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
