/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./components/menu/MyAccount.vue')['default']
    Appbar: typeof import('./components/Appbar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AuthDialog: typeof import('./components/menu/AuthDialog.vue')['default']
    CardGrid: typeof import('./components/body/CardGrid.vue')['default']
    Favorites: typeof import('./components/menu/Favorites.vue')['default']
    FilterPanel: typeof import('./components/body/FilterPanel.vue')['default']
    HelloWorld: typeof import('./components/Home.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    MyAccount: typeof import('./components/menu/MyAccount.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
